bash run_dice_exactlyOnePerPair.sh 0 && \
bash run_dice_exactlyOnePerPair.sh 1 && \
bash run_dice_exactlyOnePerPair.sh 2 && \
bash run_dice_exactlyOnePerPair.sh 3 && \
bash run_dice_exactlyOnePerPair.sh 4 && \
bash run_dice_notBoth.sh 0 && \
bash run_dice_notBoth.sh 1 && \
bash run_dice_notBoth.sh 2 && \
bash run_dice_notBoth.sh 3 && \
bash run_dice_notBoth.sh 4 && \
bash run_fashion_clothingFootwear.sh 0 && \
bash run_fashion_clothingFootwear.sh 1 && \
bash run_fashion_clothingFootwear.sh 2 && \
bash run_fashion_clothingFootwear.sh 3 && \
bash run_fashion_clothingFootwear.sh 4 && \
bash run_fashion_cr.sh 0 && \
bash run_fashion_cr.sh 1 && \
bash run_fashion_cr.sh 2 && \
bash run_fashion_cr.sh 3 && \
bash run_fashion_cr.sh 4 && \
bash run_fashion_scr.sh 0 && \
bash run_fashion_scr.sh 1 && \
bash run_fashion_scr.sh 2 && \
bash run_fashion_scr.sh 3 && \
bash run_fashion_scr.sh 4 && \
bash run_mnist_cr.sh 0 && \
bash run_mnist_cr.sh 1 && \
bash run_mnist_cr.sh 2 && \
bash run_mnist_cr.sh 3 && \
bash run_mnist_cr.sh 4 && \
bash run_mnist_scr.sh 0 && \
bash run_mnist_scr.sh 1 && \
bash run_mnist_scr.sh 2 && \
bash run_mnist_scr.sh 3 && \
bash run_mnist_scr.sh 4
